# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170619_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
